sudo: required

language: java
jdk:
  - oraclejdk8

services:
   - docker

cache:
  directories:
    - $HOME/.m2

install: true

script: travis_wait 45 docker/vespa-ci.sh

#before_script: travis_wait 45 time ./mvnw install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true

#script: travis_wait 45 time ./mvnw install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
